name: Test Flask API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t flask_app .

    - name: Run Docker container
      run: docker run -d -p 5000:5000 --name flask_app flask_app

    - name: Wait for Flask to be ready
      run: |
        echo "Waiting for Flask to start..."
        sleep 15

    - name: Test GET request
      run: |
        curl -H "X-Token: 8lGC0d8AHr98O5dM" http://localhost:5000/get_leads

    - name: Test POST request and verify response
      run: |
        response=$(curl -X POST -H "Content-Type: application/json" -H "X-Token: 8lGC0d8AHr98O5dM" -d '{"partner_name": "Random Partner", "name": "Random Lead", "phone": "123-456-7890", "email_from": "random@example.com", "x_studio_offre": "Random Offer"}' http://localhost:5000/create_lead)
        echo "Response: $response"
        if [[ $response == *'"status":"success"'* ]]; then
          echo "POST request succeeded."
          exit 0
        else
          echo "POST request failed."
          exit 1
        fi
